### ISSUE TITLE
SoaHeader.getAttachments方法实现有bug

### ISSUE THREAD

**Issue by zhangever** [isuwang/isuwang-soa#4]
业务代码:
soaHeader.getAttachments().put("key","value");
无法真正把值设置到attachments中去.

https://github.com/isuwang/isuwang-soa/blob/master/dapeng-core/src/main/java/com/isuwang/dapeng/core/SoaHeader.java

**Comment by DevotedTangLiu** [comment]
Fixed. Thank you.
